### ISSUE TITLE
Value as boolean not queryable as boolean

### ISSUE THREAD

**Issue by Dru89** [djangonauts/django-pgjson#33]
Boolean values that are saved off in a `JsonField` are only queryable as a string.

As a quick example, consider the following model:
```python
from django.db import models
from django_pgjson import fields

class Thing(models.Model):
    field = fields.JsonField()
```

And then from the terminal:
```python
t = Thing(field={'value': True})
t.save()

Thing.objects.filter(field__at_value=True)
# => []

Thing.objects.filter(field__at_value='true')
# => [<Thing>]
```

As you can see, the first query (where we treat `value` as a boolean) returns no objects.  The second query, (where we treat value as a string), returns the correct value. 

`Thing.objects.first().field['value']` returns `True`, as desired, though, so it does serialize and deserialize correctly.  The query seems to be the only thing that it doesn't accept.

**Comment by niwinz** [comment]
Is a expected behavior with json fields. The at_attributte lookup uses internally the `->>` operator that return text http://www.postgresql.org/docs/9.4/static/functions-json.html

We can't use the `->` operator that return objects because json type does not supports the `=` (equality) operator so the filters like `Thing.objects.filter(field__at_value=True)` will raise a exception.
